services:
  web:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - network

  api:
    image: kemenchik/balda:0.1.4
    ports:
      - '8081:8081'
    networks:
      - network

networks:
  network:
    driver: bridge
