/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TokenResponse } from './tokenResponse';
import type { AbstractResponseTokenResponseResponseCode } from './abstractResponseTokenResponseResponseCode';

export interface AbstractResponseTokenResponse {
  description?: string;
  payload?: TokenResponse;
  responseCode?: AbstractResponseTokenResponseResponseCode;
}
