/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AbstractResponseLongResponseCode =
  (typeof AbstractResponseLongResponseCode)[keyof typeof AbstractResponseLongResponseCode];

export const AbstractResponseLongResponseCode = {
  SUCCESS: 'SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED'
} as const;
