/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Matrix } from './matrix';
import type { Player } from './player';
import type { BoardScores } from './boardScores';

export interface Board {
  board?: Matrix;
  currentPlayer?: Player;
  id?: string;
  players?: Player[];
  scores?: BoardScores;
  startWord?: string;
  usedWords?: string[];
  version?: number;
}
