/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './abstractResponseBoard';
export * from './abstractResponseBoardResponseCode';
export * from './abstractResponseListBoard';
export * from './abstractResponseListBoardResponseCode';
export * from './abstractResponseLong';
export * from './abstractResponseLongResponseCode';
export * from './abstractResponseTokenResponse';
export * from './abstractResponseTokenResponseResponseCode';
export * from './board';
export * from './boardScores';
export * from './createGameRequest';
export * from './getBoardByIdRequest';
export * from './getBoardVersionRequest';
export * from './loginRequest';
export * from './matrix';
export * from './player';
export * from './position';
export * from './refreshTokenRequest';
export * from './registerRequest';
export * from './tokenResponse';
export * from './turn';
export * from './turnRequest';
