/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Position } from './position';

export interface Turn {
  newCharacter?: string;
  newCharacterPosition?: Position;
  positionChain?: Position[];
  word?: string;
}
