/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Turn } from './turn';

export interface TurnRequest {
  boardId?: string;
  turn?: Turn;
}
